apiVersion: apps/v1
kind: Deployment
metadata:
  name: q13-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:bookworm
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: q13-svc
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: q13-ingress
spec:
  rules:
  - host: "example.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: q13-svc
            port:
              number: 80