apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-bookworm
  labels:
    app: httpd-bookworm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-bookworm
  template:
    metadata:
      labels:
        app: httpd-bookworm
    spec:
      containers:
        - name: httpd
          image: httpd:bookworm
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service
spec:
  selector:
    app: httpd-bookworm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: "example.org"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ingress-service
                port:
                  number: 80
