apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            command: ["date"]
          restartPolicy: OnFailure