apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-date
spec:
  schedule: "*/5 * * * *"  # This runs the job every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: date-printer
              image: busybox  # A lightweight image for running simple commands
              command: ["sh", "-c", "date"]  # Command to execute
          restartPolicy: OnFailure  # Restart the job only if it fails
