apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi  # Adjust storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/db  # Local volume path