apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:bookworm
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mymount
            mountPath: "/usr/local/etc/redis"
      volumes:
      - name: mymount
        persistentVolumeClaim:
          claimName: redis-pvc