apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:bookworm
          volumeMounts:
            - name: redis-pvc-volume
              mountPath: /usr/local/etc/redis
      volumes:
        - name: redis-pvc-volume
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: database
spec:
  storageClassName: ""
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: database
spec:
  storageClassName: ""
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
