apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis:bookworm
        name: redis
        resources: {}
        volumeMounts:
          - name: config-vol
            mountPath: /usr/local/etc/redis
      volumes:
      - name: config-vol
        persistentVolumeClaim:
          claimName: myclaim          
status: {}