apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path