apiVersion: v1
kind: Pod
metadata:
  name: pod-multi
spec:
  containers:
  - name: container2
    image: busybox
    ports:
    - containerPort: 81
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 4800']
  - name: container1
    image: nginx  
    ports:
    - containerPort: 80