apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-multi
  name: pod-multi
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh','-c','sleep 4800']
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}