apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-multi
  name: pod-multi
spec:
  containers:
  - image: nginx
    name: container1
    resources: {}
  - image: busybox
    name: container2
    resources: {}
    command: ['sh', '-c', 'sleep 4800']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}