apiVersion: v1
kind: Pod
metadata:
  name: pod-multi
spec:
  containers:
  - name: container1
    image: nginx
  - name: container2
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 4800']