apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: appychip
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: appychip
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.1.0/24  
        - ipBlock:
            cidr: 10.0.0.0/24  
        - namespaceSelector:
            matchLabels:
              purpose: allowed-namespace
        - podSelector:
            matchLabels:
              role: allowed-pod
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.0/16 
      ports:
        - protocol: TCP
          port: 5978
