apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    - name: web-pod
      image: busybox:1.28
      command: ["sh", "-c", "sleep 3200"]
      securityContext:
        capabilities:
          add: ["SYS_TIME"]
