apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-pod
  name: web-pod
spec:
  containers:
  - image: busybox
    name: web-pod
    resources: {}
    command: ['sh', '-c','sleep 3200']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}