apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","3200"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]