apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: web-pod        
    image: busybox:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']