apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: web-pod
    image: busybox
    command: ['sh', '-c', 'sleep 3200']
    securityContext:
      capabilities:
        add: ["SYS_TIME"]

