apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app.kubernetes.io/name: web-pod
spec:
  containers:
  - name: web-pod
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3200']