apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    - name: busybox
      image: busybox
      securityContext:
        capabilities:
          add: ["SYS_TIME"]
      command: ["sh", "-c", "sleep 3200"]