apiVersion: batch/v1
kind: Job
metadata:
  name: web-pod
spec:
  template:
    spec:
      containers:
      - name: web-pod
        image: busybox:latest
        command: ["sleep", "3200"]
        securityContext:
          capabilities:
            add:
              - SYS_TIME
      restartPolicy: Never