apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "3200"
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
controlplane $
