apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-pod
  name: web-pod
spec:
  containers:
  - image: busybox
    name: web-pod
    command: ['sh', '-c', 'echo The app is running! && sleep 3200']