apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: newrole
  name: pod-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["create", "list"]

  ---


  apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-rolebinding
  namespace: newrole
subjects:
  - kind: User
    name: aizad
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io