apiVersion: v1
kind: ConfigMap
metadata:
  name: proj-config
data:
  MYSQL_DATABASE: "db"
  MYSQL_USER: "admin" #cannot be root
---
apiVersion: v1
kind: Secret
metadata:
  name: proj-secret
type: Opaque
data:
  MYSQL_PASSWORD: ZXhhbXBsZQ== #example
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ== #example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.40-debian
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
