apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.40-debian
        envFrom:
          - configMapRef:
              name: db-cm
          - secretRef:
              name: db-secret

