apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==  #'example'
  MYSQL_PASSWORD: ZXhhbXBsZQ==       # 'example'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_DATABASE: my_database
  MYSQL_USER: my_user
