apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/ssd
