apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
spec:
  hostPath:
    path: /mnt/ssd
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow