apiVersion: v1
kind: Pod
metadata:
  name: nginx-jaud00401
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
