apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx-jaud00401
spec:
  containers:
  - image: nginx
    name: po
    resources: {}
  nodeSelector:
    disk: ssd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}