apiVersion: v1
kind: Pod
metadata:
  name: nginx-jaud00401
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd