apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-svc
spec:
  ports:
  - port: 5432
    name: web
    targetPort: 5432
  type: NodePort
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres 
spec:
  selector:
    matchLabels:
      app: postgres  # has to match .spec.template.metadata.labels
  serviceName: "postgres-svc"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: postgres  # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres 
        image: postgres:13.16-bookworm
        env:
        - name: POSTGRES_PASSWORD
          value: "POSTGRES_PASSWORD"
        - name: POSTGRES_USER
          value: "POSTGRES_USER"
        - name: POSTGRES_DB
          value: "POSTGRES_DB"
        ports:
        - containerPort: 5432
          name: web
        volumeMounts:
        - name: www
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: www
        # mount /data/foo, but only if that directory already exists
        hostPath:
          path: /data                 # directory location on host
          type: DirectoryOrCreate