apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"  # Required for headless service
  replicas: 3  # Adjust based on your needs
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.16-bookworm
          env:
            - name: POSTGRES_PASSWORD
              value: your_password  # Replace with your desired password
            - name: POSTGRES_USER
              value: your_user  # Replace with your desired username
            - name: POSTGRES_DB
              value: your_db  # Replace with your desired database name
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi  # Adjust storage size as needed

---------------------------------

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer  # Change this based on your environment (e.g., NodePort or ClusterIP)
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
