apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.16-bookworm
        env:
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_USER
          value: fawwaz
        - name: POSTGRES_DB
          value: postgres
        ports:
        - containerPort: 5432
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi  # Adjust storage size as needed

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer  # Use NodePort if you don't have a cloud provider
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres