apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.16-bookworm
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: your_password  
            - name: POSTGRES_USER
              value: your_user 
            - name: POSTGRES_DB
              value: your_database  
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

//service

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  type: NodePort  
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000  
  selector:
    app: postgres
