apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-project
  name: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-project
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources: {}
status: {}